meta_product_name: "Split|it"
meta_title: "Split|it - Easily split bills with your friends and family"
meta_description: "Create groups and share expenses with ease by scanning receipts and let the app handle the bill splitting math!"
meta_image: "og-image.jpg"
